//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public int Event_id { get; set; }
        public int Student_id { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Student Student { get; set; }
    }
}
