//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Society()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int President_id { get; set; }
        public int Vice_President_id { get; set; }
        public int Treasurer_id { get; set; }
        public int Gs_id { get; set; }
        public int Faculty_Head_id { get; set; }
        public Nullable<int> Faculty_Cohead_id { get; set; }
        public Nullable<int> Budget_approver_id { get; set; }
        public Nullable<int> Budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        public virtual FinanceDepartment FinanceDepartment { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Teacher Teacher1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual Student Student2 { get; set; }
        public virtual Student Student3 { get; set; }
    }
}
